const resume = {
  portfolio: [
    {
      title: 'Texas Tracker',
      description: 'Follow us throughout the Texas Legislative session as we track the key issues and latest developments from the Capitol in Austin.',
      date: '1/8/2019',
      comments: '',
      preview: 'tracker',
      link: 'https://interactives.dallasnews.com/2019/texas-tracker/',
    },
    {
      title: 'The Shifting Tide',
      description: 'Beto O’Rourke’s near loss in the 2018 Senate election shows that while Texas is still red, in some parts of the state, the current may be changing.',
      date: '11/15/2018',
      comments: '',
      preview: 'politics',
      link: 'https://interactives.dallasnews.com/2018/shifting-tide-of-texas-politics',
    },
    {
      title: 'Texas schools, graded A to F',
      description: 'This school year is the first time the Texas Education Agency has issued grades to school districts in an A-F system based on how well they\'re educating kids.',
      date: '9/20/2018',
      comments: '',
      preview: 'grades',
      link: 'https://interactives.dallasnews.com/2018/texas-schools-grades/',
    },
    {
      title: 'Standoff: How the Dallas SWAT team cornered and killed the July 7 police shooter',
      description: 'This is the first full account of what happened inside El Centro College in the darkness and chaos of July 7, 2016.',
      date: '2/2/2018',
      comments: '',
      preview: 'standoff',
      link: 'https://interactives.dallasnews.com/2018/standoff/',
    },
    {
      title: 'Visualizing Adrian Beltre’s march to 3,000 hits',
      description: 'Check out a complete visualization of Adrian Beltre\'s march to 3, 000 hits',
      date: '7/30/2017',
      comments: '',
      preview: 'beltre',
      link: 'https://interactives.dallasnews.com/2017/beltre-3000-hits/',
    },
    {
      title: 'How have the Dallas Mavericks performed in the NBA draft?',
      description: 'Let\'s face it, the Dallas Mavericks don\'t have a good track record when it comes to the draft.',
      date: '6/21/2017',
      comments: '',
      preview: 'mavs',
      link: 'https://interactives.dallasnews.com/2017/mavs-draft/',
    },
    {
      title: 'How have the Dallas Cowboys performed in the NFL draft?',
      description: 'Over the years, Dallas\' picks have been a mixed bag .Here\'s our assessment of every one.',
      date: '4/24/2017',
      comments: '',
      preview: 'cowboys',
      link: 'http://interactives.dallasnews.com/2017/cowboys-draft-data/',
    },
    {
      title: 'Behind the numbers: Dak\'s rookie season',
      description: 'Statistics tell the story, one of the best the NFL has seen in a long, long time',
      date: '2/3/2017',
      comments: '',
      preview: 'dak',
      link: 'http://interactives.dallasnews.com/2017/dak-prescott-rookie-season/',
    },
    {
      title: 'The battle for America’s guns',
      description: 'Lobbyists spend millions of dollars every year trying to influence gun policy in America.',
      date: '11/18/2016',
      comments: '',
      preview: 'guns',
      link: 'http://interactives.dallasnews.com/2016/gun-fight/index.html',
    },
    {
      title: 'Dallas Cowboys Operation Game',
      description: 'The classic board game “Operation” requires steady hands. Cowboys team doctors need those too.',
      date: '9/8/2016',
      comments: '',
      preview: 'operation',
      link: 'http://interactives.dallasnews.com/2016/dallas-cowboys-operation/',
    },
  ],
  experience: [
    {
      title: 'Interactives Editor',
      time: 'April 2016 – January 2019',
      description: 'Collaborated with other journalists and developers to create original content that engages with readers through immersive storytelling applications, interactive data visualizations and other data-rich media.',
      skills: ['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4'],
    },
    {
      title: 'Graphics and Multimedia Director',
      time: '2003 – 2016',
      description: 'Led, developed and worked in the graphics and multimedia team to create visual content and data-driven journalism across multiple platforms.The role required innovative practices and strong management skills. The team\'s primary role was to create editorial content such as maps, charts, animations, interactive data visualizations and digital design presentations across multiple platforms.',
      skills: ['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4'],
    },
    {
      title: 'Multimedia Editor',
      time: '2002 – 2003',
      description: 'Created original online content while consistently exercising discretion and judgment to convey the intended message. Researched, wrote and edited long-term assignments as well as projects under tight deadlines.',
      skills: ['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4'],
    },
    {
      title: 'Senior Artist',
      time: '1998 – 2002',
      description: 'Worked closely with multiple departments to research and report a wide range of visuals used to support and accompany news and editorial coverage. Produced original graphic content including data  visualizations, illustrations and animations, often under tight deadlines.',
      skills: ['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4'],
    },
  ],
  awards: [
    {
      title: 'Award of Excellence',
      time: '2017',
      description: 'Graphics: Planned Coverage',
      winner: 'Beltre\'s March to 3,000 Hits',
      issued: 'Society of News Design',
      logo: 'snd',
      image: 'beltre',
      link: 'https://interactives.dallasnews.com/2017/beltre-3000-hits/',
    },
    {
      title: 'Award of Excellence',
      time: '2015',
      description: 'Features',
      winner: 'Lucha Libre in Dallas',
      issued: 'Society of News Design',
      logo: 'snd',
      image: 'luchalibre',
      link: 'http://interactives.dallasnews.com/2015/lucha-libre/',
    },
    {
      title: 'Award of Excellence',
      time: '2014',
      description: 'Combination Print and Digital News',
      winner: 'Dallas Cowboys Legends Quiz',
      issued: 'Society of News Design',
      logo: 'snd',
      image: 'cowboys',
      link: 'http://res.dallasnews.com/graphics/2014_09/cowboysfaces/',
    },
    {
      title: 'Award of Excellence',
      time: '2014',
      description: 'Features',
      winner: 'Final Fork',
      issued: 'Society of News Design',
      logo: 'snd',
      image: 'finalfork',
      link: 'http://res.dallasnews.com/graphics/2014_03/finalfork/',
    },
    {
      title: 'Award of Excellence (2)',
      time: '2012',
      description: 'Features, Use of Multimedia',
      winner: 'Lost Dallas',
      issued: 'Society of News Design',
      logo: 'snd',
      image: 'lostdallas',
      link: 'http://res.dallasnews.com/graphics/2012_07/lostdallas/',
    },
    {
      title: 'Award of Excellence',
      time: '2005',
      description: 'Information Graphics',
      winner: 'Twin Destinies',
      issued: 'Society of News Design',
      logo: 'snd',
      image: 'twins',
    },
    {
      title: 'Katie Award',
      time: '2004',
      description: 'Visual Communication Infographic',
      winner: 'Conjoined Twins',
      issued: 'Press Club of Dallas',
      logo: 'katie',
      image: 'twins',
    },
    {
      title: 'Katie Award',
      time: '2002',
      description: 'Web Site News Graphics',
      winner: 'Fake Drugs, Real Lives',
      issued: 'Press Club of Dallas',
      logo: 'katie',
      image: 'fakedrugs',
    },
    {
      title: 'Katie Award',
      time: '2001',
      description: 'Visual Communication Infographic',
      winner: 'Hit to Kill',
      issued: 'Press Club of Dallas',
      logo: 'katie',
      image: 'hittokill',
    },
    {
      title: 'Katie Award',
      time: '2001',
      description: 'Web Site News Graphics',
      winner: 'Galveston’s 1900 Hurricane',
      issued: 'Press Club of Dallas',
      logo: 'katie',
      image: 'galveston',
    },
    {
      title: 'Katie Award',
      time: '1999',
      description: 'Visual Communication Infographic',
      winner: 'Roaring Rapids Accident',
      issued: 'Press Club of Dallas',
      logo: 'katie',
    },
    {
      title: 'First Place',
      time: '2003',
      description: 'Infographics - Class AAAA',
      winner: '',
      issued: 'Texas Associated Press Managing Editors',
      logo: 'tapme',
    },
    {
      title: 'First Place',
      time: '2000',
      description: 'Infographics - Class AAAA',
      winner: '',
      issued: 'Texas Associated Press Managing Editors',
      logo: 'tapme',
    },
  ],
};

export default resume;
